# hortusfox/templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hortusfox.fullname" . }}-app
  labels:
    {{- include "hortusfox.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.app.service.type "NodePort") .Values.app.service.nodePort) }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hortusfox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app