apiVersion: v1
kind: Service
metadata:
  name: {{ include "hortusfox.fullname" . }}-db-headless
  labels:
    {{- include "hortusfox.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  clusterIP: None # This makes it "headless"
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "hortusfox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hortusfox.fullname" . }}-db
  labels:
    {{- include "hortusfox.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
      {{- if (and (eq .Values.db.service.type "NodePort") .Values.db.service.nodePort) }}
      nodePort: {{ .Values.db.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hortusfox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db